// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aryddpivlxqeryrbvyky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFyeWRkcGl2bHhxZXJ5cmJ2eWt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1ODU4MDYsImV4cCI6MjA2NDE2MTgwNn0.8YeLbv_y7UHtJhEoDIzv5Qj54DHdnrr9NV6B8K3Qe3s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);